/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-11-29 16:27:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.text.*;
import java.util.*;
import java.sql.*;
import java.text.*;

public final class question_005fboard_005finsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1669737791847L));
    _jspx_dependants.put("/uservalid.jsp", Long.valueOf(1669737792047L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1669737791898L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>예제문제 게시판 글작성</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/question_board_insert_style.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css\" integrity=\"sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"main_style.css\">\r\n");
      out.write("\r\n");
      out.write("<title>navbar</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>	\r\n");
      out.write("	<script>\r\n");
      out.write("	function f(link){\r\n");
      out.write("		location.href=link;\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("	<div class=\"body-box\">\r\n");
      out.write("		<div id=\"top\">\r\n");
      out.write("			<div id=\"head-top\">\r\n");
      out.write("				<div id=\"logo\">\r\n");
      out.write("					<img src=\"elephant.png\" style=\"width:30px;\">\r\n");
      out.write("					<a href=\"main.jsp\"><span id=\"page-name\">우리컴공끼리</span></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"user\">\r\n");
      out.write("					");
if(request.isRequestedSessionIdValid()&&session.getAttribute("name")!=null){ 
      out.write("\r\n");
      out.write("					<!--세션이 유효할 때  -->\r\n");
      out.write("					<span class=\"font-default\">어서오세요 ");
      out.print(session.getAttribute("name") );
      out.write("님. </span>\r\n");
      out.write("					<button class=\"btn-default\" type=\"submit\" onclick=\"f('logout.jsp')\">logout</button>\r\n");
      out.write("					");
} else{
      out.write("\r\n");
      out.write("					<!--세션이 유효하지 않을 때  -->\r\n");
      out.write("					\r\n");
      out.write("					<button class=\"btn-default\" type=\"submit\" onclick=\"f('login.jsp')\">login</button>\r\n");
      out.write("					<button class=\"btn-default\" type=\"submit\" onclick=\"f('signup.jsp')\">sign up</button>\r\n");
      out.write("					\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"nav\" class=\"navbar-default\">\r\n");
      out.write("				<ul class=\"clearfix\">\r\n");
      out.write("					<li><a href=\"free_board.jsp\">오늘도 밤새니?</a></li>\r\n");
      out.write("					<li><a href=\"question_board.jsp\">지능 UP!</a></li>\r\n");
      out.write("					<li><a href=\"contest_board.jsp\">스펙 UP!</a></li>\r\n");
      out.write("					<li><a href=\"tasty_board.jsp\">오늘 뭐 먹지?</a></li>\r\n");
      out.write("					<li><a href=\"fame_hall.jsp\">명예의 전당</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("utf-8"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>로그인이 필요한 페이지를 열었을 때</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
if(request.isRequestedSessionIdValid()&&session.getAttribute("name")!=null){ 
      out.write("\r\n");
      out.write("		<!--세션이 유효할 때  -->\r\n");
      out.write("		<script></script>\r\n");
      out.write("		");
} else{
      out.write("\r\n");
      out.write("		<!--세션이 유효하지 않을 때  -->\r\n");
      out.write("		<script>\r\n");
      out.write("			alert(\"로그인을 먼저 해주세요.\");\r\n");
      out.write("			location.href=\"login.jsp\";\r\n");
      out.write("		</script>					\r\n");
      out.write("	");
} 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write('\r');
      out.write('\n');

	int id=0;
	int ref;
	String title,writer,writer_id,content,image,time;
	int heart,reply;
	String sql=null;
    Connection conn =null;
    Statement stmt = null;
    ResultSet rs=null;
    if(request.getParameter("id")!=null)
    	id=Integer.parseInt(request.getParameter("id"));
    int id2=id+10;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        String jdbcurl = "jdbc:mysql://localhost:3306/cse_community?serverTimezone=UTC";
        conn = DriverManager.getConnection(jdbcurl,"root","qwerQWER123$");
        stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        sql="select * from question where id=ref order by id desc limit "+id+", "+id2;
        rs = stmt.executeQuery(sql);
     }catch(Exception e){
        out.print("DB 연동 오류입니다.:" + e.getMessage());
    }
    
      out.write("\r\n");
      out.write("    <div class=\"body-box\">\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <div id=\"body-left\" class=\"design\">\r\n");
      out.write("                <form id=\"form1\" action=\"question_board_insert_db.jsp\" method=\"POST\" enctype=\"multipart/form-data\">\r\n");
      out.write("                    <div id=\"title\" class=\"title-design\">\r\n");
      out.write("                        <h1><input type=\"text\" placeholder=\"제목을 입력해주세요\" name=\"title\" id=\"title-input\" size=\"40\" required></h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"main\" class=\"clearfix\">\r\n");
      out.write("                        <textarea name=\"content\" id=\"content-input\" rows=\"18\" cols=\"62\" placeholder=\"글을 입력해주세요\" class=\"design\" required></textarea> \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"line\"></div>\r\n");
      out.write("                    <div class=\"upload\">\r\n");
      out.write("                        <input class=\"file-name\" value=\"파일 선택\" disabled=\"disabled\">\r\n");
      out.write("\r\n");
      out.write("                        <label for=\"file_btn\">업로드</label>\r\n");
      out.write("                        <input type=\"file\" id=\"file_btn\" name=\"file\" class=\"file-hidden\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"move-button\" class=\"clearfix\">\r\n");
      out.write("                        <div class=\"\"><input type=\"submit\" class=\"btn-q\" value=\"확인\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

            sql="select * from question where id=ref order by ref desc ";
            rs = stmt.executeQuery(sql);
            
      out.write("\r\n");
      out.write("            <div id=\"body-right\" class=\"design\">\r\n");
      out.write("                <div id=\"sidebar-title\" class=\"title-design\">\r\n");
      out.write("                    <h2>오늘의 문제</h2><!--2개 정도만 보여주면 될듯...?-->\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"list clearfix\">\r\n");
      out.write("                ");

                while(rs.next() && rs.getRow()<=4)
                {
                	id=Integer.parseInt(rs.getString("id"));
                	ref=Integer.parseInt(rs.getString("ref"));
                	title=rs.getString("title");
                	writer=rs.getString("writer");
                	writer_id=rs.getString("writer_id");
                	content=rs.getString("content");
                	time=rs.getString("time");
                	heart=rs.getInt("heart");
                	reply=rs.getInt("reply");
                	image=rs.getString("image");
             
      out.write("\r\n");
      out.write("                    <div id=\"post-left\" class=\"design\" onclick=\"linked('question_board_post.jsp?id=");
      out.print(id);
      out.write("')\">\r\n");
      out.write("                        <div id=\"inner\" class=\"design clearfix\">\r\n");
      out.write("                            <div id=\"inner-title\" class=\"noline-design\">");
      out.print(title );
      out.write("</div>\r\n");
      out.write("                            <div id=\"inner-pic\" class=\"noline-design\"><img style=\"width:100%;\" src=\"question/");
      out.print(image );
      out.write("\" onerror=\"this.style.display='none'\"></div>\r\n");
      out.write("                            <div id=\"inner-text\" class=\"noline-design\">");
      out.print(content );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"inner-info\" class=\"clearfix\">\r\n");
      out.write("                            <div class=\"info-design-left noline-design\">");
      out.print( writer );
      out.write("</div>\r\n");
      out.write("                            <div class=\"info-design-right noline-design\" style=\"color:rgb(204,102,51);\">🗨 ");
      out.print( reply );
      out.write("</div>\r\n");
      out.write("                            <div class=\"info-design-right noline-design\">👍 ");
      out.print( heart );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css\" integrity=\"sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"main_style.css\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"body-box\">\r\n");
      out.write("		<div id=\"footer\">\r\n");
      out.write("			<div style=\"float:left; padding:10px;\">\r\n");
      out.write("				<span>dongguk university</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div style=\"float:right; padding:10px;\">\r\n");
      out.write("				<span>Copyright ⓒ COJ Corp. All Right reserved.</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("  var fileTarget = $('.upload .file-hidden');\r\n");
      out.write("\r\n");
      out.write("    fileTarget.on('change', function(){\r\n");
      out.write("        if(window.FileReader){\r\n");
      out.write("            var filename = $(this)[0].files[0].name;\r\n");
      out.write("        } else {\r\n");
      out.write("            var filename = $(this).val().split('/').pop().split('\\\\').pop();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(this).siblings('.file-name').val(filename);\r\n");
      out.write("    });\r\n");
      out.write("}); \r\n");
      out.write("    function linked(link){\r\n");
      out.write("    	location.href=link;\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
